"""empty message

Revision ID: 60ec21362805
Revises: a4ec65e5d5c6
Create Date: 2019-10-26 21:42:24.395753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ec21362805'
down_revision = 'a4ec65e5d5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'longitude')
    op.drop_column('user', 'latitude')
    # ### end Alembic commands ###
